Basic component(button, grid) 생성
cotae-platform/cotae-ui pull request #1
Opened 2023-02-06 13:18 UTC by beomseok37

### ➕ 추가한 기능
basic component 중 button을 생성했고, grid는 가볍게 row와 column 컴포넌트만 구현했습니다.

<br/>

### ❓ PR 리뷰 시 중점적으로 리뷰하고 싶은 부분

1. 현재 `yarn start`로 개발을 진행하는 도중에 자꾸 eslint error가 나타납니다....

처음 `yarn start`를 했을 경우에는 안 뜨지만 파일을 수정하면 갑자기 아래와 같은 오류가 떠서 개발 모드를 끄지 않는 이상 계속 오류가 나타나는 상황입니다...
![스크린샷 2023-02-06 22 08 45](https://user-images.githubusercontent.com/60134628/216979460-80e6f1b8-bc00-4744-b4d1-07f8a2085d32.png)

위와 같은 오류가 나타난 것을 인지하고, 여러 시도를 해봤지만 해결되지 않았습니다. 대부분이 eslint의 `parserOptions.project`에 tsconfig.json 경로를 써주면 된다고 하지만 해결되지 않았습니다. [reference](https://stackoverflow.com/questions/64116378/error-while-loading-rule-typescript-eslint-dot-notation)
**craco와 관련된 이슈**일지 모르니 확인 부탁드립니다.
<br/><br/>
2. node_modules가 계속 생성됩니다.

.yarnrc.yml에 node_linker 관련 옵션도 없는데 생성되는 이유를 알지 못했습니다...
-> **PnP에도 영향이 가는지 yarn install을 하지 않은 상태에서 바로 실행되는지** 확인 부탁드립니다.
<br/><br/>
3. /design-example url에 design example 모음을 만들어두었습니다.

개발 진행에 어려움이 있어 button 밖에 구현하지 못 했지만 한 번 확인해주세요

2023-02-06 16:02 UTC, PangHae requested changes
node_modules를 삭제하고 새로이 yarn start를 해도 node_modules 폴더는 재생성됩니다. 
zero-install에는 문제가 없고, babel-loader가 생성하는 파일이 node_modules 폴더 안에 생성되도록 CRA 자체 설정되어 있어서 그런 것으로 예상됩니다.
<img width="725" alt="image" src="https://user-images.githubusercontent.com/62276222/217021581-f95cdc99-5786-4e77-b2dd-8ef713730bca.png">
위 사진은 웹펙 공식 사이트 babel-loader 설명 docs에서 가져왔습니다.

CRA를 eject하지 않는 이상, webpack.config.js파일을 건드릴 수 없기 때문에 크게 신경쓰지 않아도 될 것 같습니다.

2023-02-06 16:04 UTC, PangHae commented
버튼 제작하느라 고생하셨습니다..!!!!

2023-02-06 16:08 UTC, PangHae commented on .eslintrc.json
>    "parserOptions": {
이 부분은 제가 eslint 추가만 새로해서 push 해놨으니 확인 부탁드립니다! 
import를 작성했을 때 나타나는 warning 처리 방식에 대해서 논의하면 될 것 같습니다.

2023-02-07 01:01 UTC, beomseok37 commented on .eslintrc.json
>    "parserOptions": {
오 좋네요~ 혹시 관련 reference를 알 수 있을 까요??

2023-02-07 01:06 UTC, beomseok37 commented on src/components/basic/Grid/Column/index.tsx
> +    <CommonGrid direction="column" justifyContent={justifyContent!} alignItems={alignItems!}>
github에서 추천하는 방식인 옵셔널 체이닝으로 가는 것이 좋을 같네요👍

2023-02-08 07:30 UTC, PangHae approved these changes

2023-02-08 07:31 UTC, merged