Add Dropdown Component
cotae-platform/cotae-ui pull request #3
Opened 2023-02-08 09:12 UTC by PangHae

### ➕ 추가한 기능
Dropdown Component 추가
- Dropdown Component 외부 클릭 시, menu들이 닫히도록 설정
- 선택된 value는 색이 다르도록 styling

<br/>

### ❓ PR 리뷰 시 중점적으로 리뷰하고 싶은 부분
1. Props로 items => dropdown에 보여주고 싶은 item list, onChange => dropdown 항목 변경 시, 외부에서도 변경할 수 있도록 하는 함수를 사용하였습니다. 이 외에 새로이 추가할 것으로 예상되는 Props들이 있을까요?
2. items type을 string[]으로 선언하였는데 {text : string, value : string}[]으로 타입을 변경하여 dropbox menu에 보이는 값은 text, 실제 사용되는 데이터는 value로 조정하는 것이 좋을까요?
3. Dropdown에 사용된 style.ts가 의도한 바대로 알맞게 사용되었는지 확인 부탁드립니다.

2023-02-08 13:05 UTC, beomseok37 commented on src/components/basic/Dropdown/index.tsx
> +  };
함수명 한 번 확인해주세요~

2023-02-08 13:30 UTC, beomseok37 requested changes
handleClickOutside 구현이 좋네요👍

현재 구현을 pull 받아서 design-example에서 직접 봤는데, dropdown 아래 다른 컴포넌트가 있을 경우 dropdown이 열리면 아래 컴포넌트가 펼쳐진 dropdown 아래로 밀리게 되네요!
이 부분만 고쳐주세요~

2023-02-09 00:46 UTC, PangHae commented on src/components/basic/Dropdown/index.tsx
> +  };
수정했습니다!

2023-02-09 00:47 UTC, PangHae commented on src/components/basic/Dropdown/index.tsx
> +      setIsOpen(false);
오 생략된 줄 몰랐네요 감사합니다,, 좋은 레퍼런스도 감사합니다

2023-02-09 01:19 UTC, PangHae commented
> handleClickOutside 구현이 좋네요👍
> 
> 현재 구현을 pull 받아서 design-example에서 직접 봤는데, dropdown 아래 다른 컴포넌트가 있을 경우 dropdown이 열리면 아래 컴포넌트가 펼쳐진 dropdown 아래로 밀리게 되네요! 이 부분만 고쳐주세요~

수정하였습니다~~ 확인 부탁드립니다!

2023-02-09 08:47 UTC, beomseok37 approved these changes
굳잡

2023-02-09 08:47 UTC, merged