input
cotae-platform/cotae-ui pull request #4
Opened 2023-02-11 05:15 UTC by beomseok37

### ➕ 추가한 기능

<br/>

### ❓ PR 리뷰 시 중점적으로 리뷰하고 싶은 부분

2023-02-12 13:46 UTC, PangHae requested changes
고생하셨습니다! 
별개로 table 컴포넌트 제작 중인데 rc-table이라는 라이브러리를 받고, 스타일이나 기능을 추가로 개발해 basic 컴포넌트로 사용하는 방안을 생각하고 있는데 어떤지 의견 주시면 감사하겠습니다.

2023-02-12 13:46 UTC, PangHae commented on src/components/basic/Input/style.ts
> +`;
![image](https://user-images.githubusercontent.com/62276222/218313825-f8e35ade-6279-4029-86f8-ee1841a0353b.png)

실행에는 문제가 없는데, 혹시 같은 오류 발생하는지 확인 부탁드립니다!

2023-02-12 13:46 UTC, PangHae commented on src/components/basic/Input/style.ts
> +  color: #999;
focus되었을 때, placeholder가 텍스트 박스 border로 이동하는데 이때 글자색은 변경되는게 좋을 것 같습니다! 글자색을 border 색으로 변경하는 건 어떨까요?

2023-02-12 13:46 UTC, PangHae commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
useInput으로 value와 onChange를 hook으로 만드는 것은 좋은 아이디어인 것 같습니다. 추가하고 싶은 아이디어가 있습니다.
onChange에 조건부로 변경하고 싶을 경우가 있을 것으로 생각됩니다.
ex) 정규식 판별로 value가 입력될 지 말지 결정 등,,

useInput의 initialValue로 조건식을 추가하는 방안에 대해 어떻게 생각하시는지 알려주시면 감사하겠습니다!
아래는 제가 생각한 예시입니다.

```jsx
import { ChangeEvent, useState } from 'react';

interface Props{
 initialState: string;
 condition?: boolean;
}

function useInput({initialState, condition}:Props) {
  const [state, setState] = useState(initialState);

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    if(condition){
      setState(e.target.value);
    }
  };

  return { state, handleChange };
}

export default useInput;

```

2023-02-12 13:52 UTC, beomseok37 commented on src/components/basic/Input/style.ts
> +  color: #999;
넵!

2023-02-12 14:07 UTC, beomseok37 commented on src/components/basic/Input/style.ts
> +`;
저는 발생하지 않네요!

2023-02-12 14:13 UTC, beomseok37 commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
input에 정규식을 써서 입력을 막는 경우가 저희 프로젝트에서 쓰일 수 있는 부분을 알려주세요!
와이어프레임의 어떤 부분에서 input 사용 시 정규식을 사용해서 입력을 막을 것인지 알려주시면 될 것 같습니다!

2023-02-12 14:16 UTC, beomseok37 commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
그리고 condition이 정규식으로 현재 입력된 것에 대한 정규식 판별 결과 인 것 같은데, 위의 로직이 원하는대로 동작될지 잘 모르겠네요!

위와 같이 useInput({initialState,condition})을 사용했을 경우 condition에는 어떤 인자가 들어가는지 알려주시면 이해가 될 것 같습니다!

2023-02-13 00:44 UTC, PangHae commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
다른 input에는 사용할 일은 없을 듯 한데 id 제한을 두거나 비밀번호 형식 확인할 때 사용할 것으로 생각하였습니다.
인자로는 
```jsx
const regex = /^~~~~~$/g

useInput({initialState : '', condition : regex.test(password)}) 
```
을 생각하였습니다

2023-02-13 01:25 UTC, beomseok37 commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
그럼
```ts
const {state : password, handleChange} = useInput({initialState : '', condition : regex.test(password)}) 
```
이런 식으로 사용하는 것이 맞을까요??..

2023-02-13 01:41 UTC, PangHae commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
넵!! 맞습니다. 추가하는 것에 대해선 괜찮다고 생각하시나요?

2023-02-13 01:57 UTC, beomseok37 commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
추가하는 것에 대해서는 좋은 것 같습니다.
하지만, 로직 관련해서는 잘 동작하지 않을 것 같습니다...

유효성 검사로 입력을 막는 것 + 사용자에게 잘못된 입력이 들어갔다는 표시가 생길 수 있도록하는 고도화 하는 작업을 다음 피알로 하는게 어떨까 싶습니다.

이번 input 리뷰를 받고 느낀 점이 `ButtonHTMLAttributes`, `InputHTMLAttributes`을 통한 인터페이스 확장을 제대로 사용하지 않다는 것을 느꼈습니다.
그래서 리팩토링한 것을 다음 피알로 올릴 생각인데, 그 과정에서 위의 input 고도화 작업도 한 번 진행해보겠습니다.

2023-02-13 02:01 UTC, PangHae commented on src/hooks/useInput.ts
> +function useInput(initialState: string) {
넵 알겠습니다!! 
버튼 리팩토링 진행하시면서 아래 영상은 피그마 실행 영상인데, 영상처럼 버튼에 hover 등의 interaction도 같이 추가되면 좋을 것 같습니다.
저도 dropdown refactoring 할 부분 + table 컴포넌트 같이 PR 올리겠습니다.
고생하셨습니다!!!!

https://user-images.githubusercontent.com/62276222/218354048-87831d2b-abb5-4ab7-8c49-eb2ddcdaa01f.mov

2023-02-13 02:02 UTC, PangHae approved these changes

2023-02-13 02:03 UTC, merged